### ISSUE TITLE
error: ‘class BT::StdCoutLogger’ has no member named ‘failed_Node’

### ISSUE THREAD

**Issue by sz-123** [husikl/dbt_ros#1]
dbt_executor.cpp:238:25: error: ‘class BT::StdCoutLogger’ has no member named ‘failed_Node’
  238 |         failedN =logger.failed_Node;
      |                         ^~~~~~~~~~~
make[2]: *** [CMakeFiles/dbt_executor.dir/build.make:63: CMakeFiles/dbt_executor.dir/src/dbt_executor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:360: CMakeFiles/dbt_executor.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by husikl** [comment]
Basically I adjusted the original BehaviorTree.CPP package. You can use mine if you just want to test the code. I will make it compatible with latest BehaviorTree.CPP later on. The idea was just to adjust the cout logger to return the name of failed node and use it as input to the tree generator script. You can take a look inside the BehaviorTree.CPP/src/loggers/bt_cout_logger.cpp from following zip file or use it instead of the latest BehaviorTree.CPP package
[BehaviorTree.CPP.zip](https://github.com/husikl/dbt_ros/files/12917112/BehaviorTree.CPP.zip)

**Comment by sz-123** [comment]
Thanks for the swift response!
